In [1]:
import numpy as np
from numpy.linalg import inv

In [2]:
data = np.genfromtxt('data_n_Y.dat',
                     names=None,
                     dtype=np.float32,
                     delimiter='   ')

In [3]:
y1 = data[:,1]
y2 = data[:,2]
y3 = data[:,3]

In [4]:
y = np.array([[np.mean(y1), np.mean(y2), np.mean(y3)]]).T
y

array([[ 9.921828],
       [10.201736],
       [ 9.761474]], dtype=float32)

In [5]:
C = np.array([[1, 1, 1]]).T
C

array([[1],
       [1],
       [1]])

In [6]:
R = np.cov([y1, y2, y3], rowvar=1)
R

array([[ 0.91525891,  0.12397291, -0.23751877],
       [ 0.12397291,  2.11038947, -0.32122053],
       [-0.23751877, -0.32122053,  5.19280648]])

In [7]:
x = inv(C.T @ inv(R) @ C) @ C.T @ inv(R) @ y
x

array([[9.96715086]])